---
- name: MatterBridge | Create container directories
  file:
    path: '{{ item }}'
    state: directory
    owner: dockremap
    group: docker
    recurse: true
  with_items:
    - '{{ matterbridge_cont_vol }}/config'
    - '{{ matterbridge_cont_vol }}/data'

- name: MatterBridge | Generate YAML configuration
  template:
    src: 'matterbridge.yaml.j2'
    dest: '{{ matterbridge_cont_vol }}/config/matterbridge.yaml'
    owner: dockremap
    group: docker
  register: config_file

- name: MatterBridge | Copy over Status node config
  copy:
    src:   'node_config.json'
    dest:  '{{ matterbridge_cont_vol }}/config/node.json'
    owner: 'dockremap'
    group: 'docker'
  register: node_config_file
