---
- name: Create Consul service definition
  include_role: name=infra-role-consul-service
  vars:
    consul_config_name: '{{ matterbridge_service_name }}'
    consul_services:
      - id:   '{{ matterbridge_service_name }}'
        name: '{{ matterbridge_service_name }}'
        tags: ['matterbridge', 'bridge']
        checks:
          - id:   '{{ matterbridge_service_name }}-health'
            name: 'MatterBridge API health'
            type: 'tcp'
            tcp:  '0.0.0.0:{{ matterbridge_api_port }}'
