---
- name: MatterBridge | Create compose file
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ matterbridge_compose_file }}'
    owner: 'dockremap'
    group: 'docker'
    mode: 0644

- name: MatterBridge | Create container
  docker_compose:
    project_src: '{{ matterbridge_service_path }}'
    pull: true
    state: '{{ compose_state }}'
    restarted: '{{ compose_restart }}'
    recreate: '{{ compose_recreate }}'
