---
- name: MatterBridge | Create container
  docker_container:
    name: '{{ matterbridge_cont_name }}'
    image: '{{ matterbridge_cont_image }}'
    pull: true
    restart_policy: always
    state: '{{ cont_state }}'
    recreate: '{{ cont_recreate }}'
    restart: '{{ config_file.changed or cont_restart }}'
    volumes:
      - '{{ matterbridge_cont_vol }}/matterbridge.yaml:/matterbridge.yaml'
    ports: '{{ [lookup("vars", "docker_api_port")] if lookup("vars", "matterbridge_api_enabled") else [] }}'
    command: |
      -conf=/matterbridge.yaml
      {% if matterbridge_debug %}-debug{% endif %}
  vars:
    docker_api_port: '{{ matterbridge_api_port }}:{{ matterbridge_api_port }}'
