---
- name: MatterBridge | Create compose file
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ matterbridge_compose_file }}'
    owner: 'dockremap'
    group: 'docker'
    mode: 0644

- name: MatterBridge | Create container
  community.docker.docker_compose_v2:
    project_src: '{{ matterbridge_service_path }}'
    recreate:    '{{ compose_recreate }}'
    pull:        '{{ compose_pull }}'
    state:       '{{ "restarted" if config_file.changed else compose_state }}'
